name: 'Run Linter'

on:
  push:
    branches: ['master']
    paths:
      - 'express/**'
      - 'nest/**'
      - '.github/workflows/*'
  pull_request:
    branches:
      - master
    paths:
      - 'express/**'
      - 'nest/**'
      - '.github/workflows/*'

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.1

      - run: corepack enable

      - name: Install deps
        run: yarn

      - name: Run test express
        run: cd express && yarn test

      - name: Run test nest
        run: cd ../nest && yarn test
